# Generated by Django 4.1 on 2022-12-05 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True, max_length=60)),
                ('form', models.CharField(choices=[('FLACON', 'FL'), ('BOITE', 'BT'), ('TUBE', 'TB'), ('CARTON', 'CT')], default='BOITE', max_length=20)),
                ('dosage', models.CharField(blank=True, max_length=60)),
                ('price', models.FloatField(default=0.0)),
                ('is_available', models.BooleanField(default=True)),
                ('in_amo', models.BooleanField(default=False)),
                ('stockMin', models.IntegerField()),
                ('stockMax', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='image/products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
